### ISSUE TITLE
eeshenggoh - Custom Oracle is missing a function used for price hence enabling DoS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#20]
eeshenggoh

High

# Custom Oracle is missing a function used for price hence enabling DoS

## Summary
Currently, Midas has a custom aggregator for the mToken prices, which is Chainlink-compatible and we gonna use it for mToken prices. 
## Vulnerability Detail
The problem arise in `DepositVault::_calcAndValidateDeposit` which calls `_convertUsdToMToken`. The functions calls the contract `mTokenDataFeed` which was initialized in `__ManageableVault_init`. We can see that the implementation uses IDataFeed interface which contains `function getDataInBase18()`. 

However `DataFeed.sol` and  `MBasisCustomAggregatorFeed.sol and MTBillCustomAggregatorFeed.sol` inherits `CustomAggregatorV3CompatibleFeed.sol` abstract contract does not have the function `getDataInBase18()`.
```solidity
    function __ManageableVault_init(
        address _ac,
        MTokenInitParams calldata _mTokenInitParams,
        ReceiversInitParams calldata _receiversInitParams,
        InstantInitParams calldata _instantInitParams,
        address _sanctionsList,
        uint256 _variationTolerance,
        uint256 _minAmount
    ) internal onlyInitializing {
    -- SNIP --
mTokenDataFeed = IDataFeed(_mTokenInitParams.mTokenDataFeed);
```
```solidity
//DepositVault.sol
    function _convertUsdToMToken(uint256 amountUsd)
        internal
        view
        returns (uint256 amountMToken, uint256 mTokenRate)
    {
        require(amountUsd > 0, "DV: amount zero");
        //@audit-issue mToken uses customDataFeed and is missing getDataInBase18 function
        mTokenRate = mTokenDataFeed.getDataInBase18();
        require(mTokenRate > 0, "DV: rate zero");

        amountMToken = (amountUsd * (10**18)) / mTokenRate;
    }
```
Same problem applies to Redemption contract.
```solidity
//RedemptionVault.sol
    function _convertMTokenToUsd(uint256 amountMToken)
        internal
        view
        returns (uint256 amountUsd, uint256 mTokenRate)
    {
        require(amountMToken > 0, "RV: amount zero");

        mTokenRate = mTokenDataFeed.getDataInBase18();
        require(mTokenRate > 0, "RV: rate zero");

        amountUsd = (amountMToken * mTokenRate) / (10**18);
    }

    function _redeemRequest(address tokenOut, uint256 amountMTokenIn)
        internal
        returns (uint256)
    {
    -- SNIP -- 
        uint256 mTokenRate = mTokenDataFeed.getDataInBase18();
    -- SNIP -- 
```
Same issues applies to `MBasisRedemptionVaultWithSwapper`: 
```solidity
    function _swapMBasisToMToken(uint256 mBasisAmount)
        internal
        returns (uint256 mTokenAmount)
    {
-- SNIP --

        uint256 mTbillRate = mTbillRedemptionVault
            .mTokenDataFeed()//@audit-issue
            .getDataInBase18();
        uint256 mTokenRate = mTokenDataFeed.getDataInBase18(); //@audit-issue
        mTokenAmount = (mBasisAmount * mTokenRate) / mTbillRate;

-- SNIP --
    }
```
Note: The test contract uses a mock datafeed which inherits Chainlink DataFeed hence it was "working" in test case.
## Impact
Users cannot deposit tokens into protocol bricking the protocol.
## Code Snippet
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L436
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L466
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L401
## Tool used

Manual Review

## Recommendation
Ensure that `CustomAggregatorV3CompatibleFeed.sol` contains the `getDataInBase18()` function.

**Comment by goheesheng** [comment]
Escalate
The comment is not elaborating. Readme stated that Admin uses custom oracle for mToken price feed and to further support my point, the code comments stated `CustomAggregatorV3CompatibleFeed` is used to submit data prices. There isn't much in terms of how full oracle works, but since it is stated in readme and code comments how mToken price feed will be used here. It is unfair if it's intended assumption since readme and code comment has stated otherwise.
```solidity
/**
 * @title CustomAggregatorV3CompatibleFeed
 * @notice AggregatorV3 compatible feed, where price is submitted manually by feed admins
 * @author RedDuck Software
 */
abstract contract CustomAggregatorV3CompatibleFeed is
```

**Comment by sherlock-admin3** [comment]
> Escalate
> The comment is not elaborating. Readme stated that Admin uses custom oracle for mToken price feed and to further support my point, the code comments stated `CustomAggregatorV3CompatibleFeed` is used to submit data prices. There isn't much in terms of how full oracle works, but since it is stated in readme and code comments how mToken price feed will be used here. It is unfair if it's intended assumption since readme and code comment has stated otherwise.
> ```solidity
> /**
>  * @title CustomAggregatorV3CompatibleFeed
>  * @notice AggregatorV3 compatible feed, where price is submitted manually by feed admins
>  * @author RedDuck Software
>  */
> abstract contract CustomAggregatorV3CompatibleFeed is
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
As I understand, the report is incorrect. The `DataFeed` contract has the `getDataInBase18` function. Also, `DataFeed` contract has aggregator V3 variable. That's where the custom aggregators will be linked to get the data into `DataFeed` and the `getDataInBase18` will always be called in `DataFeed`.

Hence, planning to reject the escalation and leave the issue as it is, as it's incorrect.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [goheesheng](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/20/#issuecomment-2325109090): rejected
