### ISSUE TITLE
meltedblocks - Instant Redeem and Deposit Limits Can Be Abused - DoS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#26]
meltedblocks

Medium

# Instant Redeem and Deposit Limits Can Be Abused - DoS

### Summary

A malicious user can deposit and redeem within the same block. This way attacker can drain daily limits.  This attack becomes feasible and incurs no cost for the attacker (other than gas fees), if Midas team set fees to 0%. 

The Midas team has stated that:
_All percentages should be ≤ 100%, and all percentages for fees should be ≥ 0% (except for ManageableVault::variationTolerance, which should be > 0%)_.

### Root Cause

There is a daily limit on the number of tokens that can be deposited and redeemed. Both the instantDeposit and instantRedeem functions have this protection through the [_requireAndUpdateLimit](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L113) function.

Since the Midas team allows fees to drop to 0% - as specified in [_validateFee](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/abstract/ManageableVault.sol#L583) - it is possible for a malicious actor to deposit and redeem within the same transaction. The attack is feasible because the stablecoin is always 1:1, and the exchangeRatio does not change automatically (it is manually updated by the team). By following the deposit-redeem flow, the attacker would receive the same amount of USDC tokens back, while the daily limits would be targeted and fulfilled, preventing other users from performing instant deposits and redemptions on the same day.

### Internal pre-conditions

1. Admin sets `additionalFee`, `tokenFee` and `instantFee` to 0%.

### External pre-conditions
None

### Attack Path
1. Consider a daily limit of 100 tokens.
2. The attacker deposits 100 tokens.
3. In the same transaction, the attacker redeems 100 tokens.
4. Since fees are 0%, the attacker can redeem the same amount they deposited.
5. The daily limit is now reached, preventing other users from performing instant token deposits and redemptions.

### Impact
An attacker can exhaust the daily limit of deposits and redemptions, preventing other users from using the instant deposit and instant redeem functionalities.

### Mitigation
Do not allow the `instantFee` to drop to 0%; it should always be above 0% to disincentivize attackers from performing a DoS attack on daily limits.

**Comment by meltedblocks** [comment]
the attacker require amount of USDC to reach the maximum allowance - it can be done using flashloans. 

I don't get user can subscribe request

**Comment by meltedblocks** [comment]
escalate

1. The attacker require amount of USDC to reach the maximum allowance - it can be done using flashloans.
2. Don't get user can subscribe request, user can do second flow, but still instant flow is blocked

**Comment by sherlock-admin3** [comment]
> escalate
> 
> 1. The attacker require amount of USDC to reach the maximum allowance - it can be done using flashloans.
> 2. Don't get user can subscribe request, user can do second flow, but still instant flow is blocked

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
