### ISSUE TITLE
WildSniper - 0.997 and 1.003 USDC peg implementation allows for arbitraging

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#62]
WildSniper

High

# 0.997 and 1.003 USDC peg implementation allows for arbitraging

## Summary
usdc is assumed to be 1 to 1 usd at 0.997 and 1.003 rates, allowing for MEV to drain funds by arbitraging the price difference instantly
## Vulnerability Detail
in `ManageableVault` we have function `_getTokenRate`

```solidity
File: ManageableVault.sol
603:     function _getTokenRate(address dataFeed, bool stable)
604:         internal
605:         view
606:         returns (uint256)
607:     {
608:         // @dev if dataFeed returns rate, all peg checks passed
609:         uint256 rate = IDataFeed(dataFeed).getDataInBase18();
610: 
611:         if (stable) return STABLECOIN_RATE;
612: 
613:         return rate;
614:     }
```
Its used to return the rate of the token passed to usd (basically the price) from the chainlink oracle

[in Here](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/52b77ba39be51f18a5b0736dfbe7f2acbbeba6e3/midas-contracts/contracts/feeds/DataFeed.sol#L107-L109) The checks are that if min and max are 0.997 and 1.003 then the txn don't revert

and in `_getTokenRate` we return `STABLECOIN_RATE` which is 1e18 (rate) if its stable

now the problem is that associated with those flags, a user can do the following:
1. `depositInstant` 200K usdc -> 199,400usd value -> 200,000 USD value of mToken (fees as minimum would be 40 USD)
2. `redeemInstant` 200,000 USD value of mToken (fees as minimum would be 40 USD) -> 200,000 USD value of FIAT
   - or he can redeem it for 200K USD value of WBTC
    
This is clearly leakage of value as this can be repeated multiple times.

**Constraints** are low fees of the protocol, the user being `greenlisted` or `greenlistEnabled` is false, the peg is not very close to 1 to 1

All values above are viable scenarios described by the protocol in their readMe and their Notion link

Txn fees are accounted for as l2 (ie arbitrum, thats why i neglected it)
## Code Snippet
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/52b77ba39be51f18a5b0736dfbe7f2acbbeba6e3/midas-contracts/contracts/abstract/ManageableVault.sol#L603-L614
## Tool used

Manual Review

## Recommendation
return the usdc -> usd rate and account the amount with it, don't assume the 1 to 1 cause it will lead to arbitraging and leakage of funds

**Comment by IWildSniperI** [comment]
Escalate

Although this is intended design, i clearly showed in the report how an attacker can extract value over time

Intended designs are not out-of-scope by default so this is not a reason for excluding the issue

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Although this is intended design, i clearly showed in the report how an attacker can extract value over time
> 
> Intended designs are not out-of-scope by default so this is not a reason for excluding the issue

You've deleted an escalation for this issue.

**Comment by IWildSniperI** [comment]
Escalate

Responding to judge comment 
> Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.

Here There are clear loss of funds and attacker benefit

To reclarify:
1. attacker instant deposit with 199,400USD in usdc -> gets 200,000 USD value of mToken
2. Instant Redeem the mToken for 200,000 USD of BTC
3. swap the btc for 200,600 USDC

and the attacker keeps repeating

The readMe stated that 

> Stable Pricing: The system currently assumes that the price of one stablecoin is equal to one dollar. This is a design choice

and as i calrified above by sherlock rules that design choices doesn't apply here due to loss of funds

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Responding to judge comment 
> > Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.
> 
> Here There are clear loss of funds and attacker benefit
> 
> To reclarify:
> 1. attacker instant deposit with 199,400USD in usdc -> gets 200,000 USD value of mToken
> 2. Instant Redeem the mToken for 200,000 USD of BTC
> 3. swap the btc for 200,600 USDC
> 
> and the attacker keeps repeating
> 
> The readMe stated that 
> 
> > Stable Pricing: The system currently assumes that the price of one stablecoin is equal to one dollar. This is a design choice
> 
> and as i calrified above by sherlock rules that design choices doesn't apply here due to loss of funds

You've deleted an escalation for this issue.

**Comment by IWildSniperI** [comment]
Escalate

according to sherlock rules

> Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.

Here There are clear loss of funds and attacker benefit

To reclarify:

1. attacker instant deposit with 199,400USD in usdc -> gets 200,000 USD value of mToken
2. Instant Redeem the mToken for 200,000 USD of BTC
3. swap the btc for 200,600 USDC

and the attacker keeps repeating

The readMe stated that

> Stable Pricing: The system currently assumes that the price of one stablecoin is equal to one dollar. This is a design choice

and as i calrified above by sherlock rules that design choices doesn't apply here due to loss of funds

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> according to sherlock rules
> 
> > Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.
> 
> Here There are clear loss of funds and attacker benefit
> 
> To reclarify:
> 
> 1. attacker instant deposit with 199,400USD in usdc -> gets 200,000 USD value of mToken
> 2. Instant Redeem the mToken for 200,000 USD of BTC
> 3. swap the btc for 200,600 USDC
> 
> and the attacker keeps repeating
> 
> The readMe stated that
> 
> > Stable Pricing: The system currently assumes that the price of one stablecoin is equal to one dollar. This is a design choice
> 
> and as i calrified above by sherlock rules that design choices doesn't apply here due to loss of funds

You've deleted an escalation for this issue.
