### ISSUE TITLE
hongzhong - Lack of refund mechanism will bring financial losses to owners of rejected deposit requests

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-midas-minter-redeemer-judging#84]
hongzhong

High

# Lack of refund mechanism will bring financial losses to owners of rejected deposit requests

### Summary

The deposit request process lacks a refund mechanism. Specifically, if a user requests a deposit via the depositRequest() function but the request is rejected, the user will not get refunded with the deposited value.

### Root Cause

The rejectRequest function doesn't refund the deposited tokens.

https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/DepositVault.sol#L243-L255

**Comment by 0xRandluck** [comment]
admin transferrs funds to users manally in case of rejection.
