### ISSUE TITLE
pkqs90 - BUIDL redemption may fail due to minimum redemption limit, causing the redeem of `RedemptionVaultWIthBUIDL` to DoS.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-midas-minter-redeemer-judging#98]
pkqs90

High

# BUIDL redemption may fail due to minimum redemption limit, causing the redeem of `RedemptionVaultWIthBUIDL` to DoS.

## Summary

BUIDL redemption may fail due to minimum redemption limit, causing the redeem of `RedemptionVaultWIthBUIDL` to DoS.

## Vulnerability Detail

According to the [specs](https://ludicrous-rate-748.notion.site/8060186191934380800b669406f4d83c?v=35634cda6b084e2191b83f295433efdf&p=927832e82a874221996c1edcc1d94b17&pm=s), there is a 250k minimum redemption limit for BUIDL tokens.

> Redeem the full BUIDL balance in the smartcontract if the BUIDL balance will be less than 250k post transaction (as 250k is the minimum).
Make this 250k threshold a parameter that can be adjusted by the admin

The limit is also documented here: https://www.steakhouse.financial/projects/blackrock-buidl.

> However, shares cannot be sold back unless their total value is at least $250,000, or if an exception is granted. 

The issue is that when trying to redeem BUIDL token, the current implementation only redeems the amount required for this transaction, and it may very well be below minimum redemption limit, and would cause DoS. Example:

0. There are 60k USDC and 1M BUIDL tokens in the contract in the beginning.
1. User redeems 100k mToken, which is worth 100k USDC (ignoring fees for simplicity).
2. Since there are 60k USDC left in contract, the contract tries to redeem 100k - 60k = 40k BUIDL to USDC.

However, since there is a 250k minimum redemption limit, the redeem would fail.

The correct implementation should be to redeem 250k BUIDL, and transfer 100k USDC to user. In the end, there should be 60k + 250k - 100k = 210k USDC and 1M - 250k = 750k BUIDL left in the contract.

```solidity
    function redeemInstant(
        address tokenOut,
        uint256 amountMTokenIn,
        uint256 minReceiveAmount
    )
        external
        override
        whenFnNotPaused(this.redeemInstant.selector)
        onlyGreenlisted(msg.sender)
        onlyNotBlacklisted(msg.sender)
        onlyNotSanctioned(msg.sender)
    {
        ...
        _checkAndRedeemBUIDL(tokenOutCopy, amountTokenOutWithoutFeeFrom18);
        ...
    }

    function _checkAndRedeemBUIDL(address tokenOut, uint256 amountTokenOut)
        internal
    {
        uint256 contractBalanceTokenOut = IERC20(tokenOut).balanceOf(
            address(this)
        );
        if (contractBalanceTokenOut >= amountTokenOut) return;

        uint256 buidlToRedeem = amountTokenOut - contractBalanceTokenOut;

        buidl.safeIncreaseAllowance(address(buidlRedemption), buidlToRedeem);

        // BUG: buidlToRedeem may be smaller than 250k redemption limit.
@>      buidlRedemption.redeem(buidlToRedeem);
    }
```

## Impact

Redeeming mToken in `RedemptionVaultWIthBUIDL` may DoS.

## Code Snippet

- https://github.com/sherlock-audit/2024-08-midas-minter-redeemer/blob/main/midas-contracts/contracts/RedemptionVaultWithBUIDL.sol#L164-L176

## Tool used

Manual Review

## Recommendation

If the required amount of USDC is less than minimum redemption limit (250k), redeem up to the minimum redemption limit to avoid DoS.

**Comment by rickkk137** [comment]
Escalate
duplicate of #100

**Comment by pkqs90** [comment]
@rickkk137 Obviously not a dup.

Scenario: Vault has 300k USDC, user wants to redeem 310k. Code will try to redeem 10k BUIDL, which would DoS. #100 talks about something completely different.

**Comment by pashap9990** [comment]
root cause is same for both

**Comment by 0xklapouchy** [comment]
@rickkk137 @pkqs90 Not even a duplicate.

Invalid issue.

There is no `min redemption` amount requirement or blocker within the Redeem or Settlement contracts:

- Redemption: [Etherscan link](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53#code)
- Settlement: [Etherscan link](https://etherscan.io/address/0x57Dd4E92712b0fBC8d3f3e3645EebCf2600aCef0#code)

The only valid limitation is the one mentioned in issue #100, which specifies a minimum balance requirement (if used as current is 0) within the BUILD token contract.

To reiterate, there is no `min redemption` requirement enforced by the smart contracts on the Ethereum network.

The referenced $250,000 worth of shares redemption is not related to the BUILD token redemption for USDC that can be done on-chain. If we consider this amount, it is also missing the requirement that "it needs to be submitted to the Transfer Agent between 8:00 a.m. and 3:00 p.m."

A brief description of the BUILD to USDC redemption process is provided in section `1.4. USDC Liquidity Facility`.

Additionally, the Steakhouse Financial post is not a Readme or a Specification for the audit; it should only be used to gain a better understanding of how Blackrock Tokenized T-Bills work.

**Comment by piken** [comment]
Escalate
Invalid issue
As @0xklapouchy said, [`buidlRedemption.redeem()`](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53#code) doesn't have any minimum limitation restriction. 
> @rickkk137 @pkqs90 Not even a duplicate.
> 
> Invalid issue.
> 
> There is no `min redemption` amount requirement or blocker within the Redeem or Settlement contracts:
> 
> * Redemption: [Etherscan link](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53#code)
> * Settlement: [Etherscan link](https://etherscan.io/address/0x57Dd4E92712b0fBC8d3f3e3645EebCf2600aCef0#code)
> 
> The only valid limitation is the one mentioned in issue #100, which specifies a minimum balance requirement (if used as current is 0) within the BUILD token contract.
> 
> To reiterate, there is no `min redemption` requirement enforced by the smart contracts on the Ethereum network.
> 
> The referenced $250,000 worth of shares redemption is not related to the BUILD token redemption for USDC that can be done on-chain. If we consider this amount, it is also missing the requirement that "it needs to be submitted to the Transfer Agent between 8:00 a.m. and 3:00 p.m."
> 
> A brief description of the BUILD to USDC redemption process is provided in section `1.4. USDC Liquidity Facility`.
> 
> Additionally, the Steakhouse Financial post is not a Readme or a Specification for the audit; it should only be used to gain a better understanding of how Blackrock Tokenized T-Bills work.

**Comment by sherlock-admin3** [comment]
> Escalate
> Invalid issue
> As @0xklapouchy said, [`buidlRedemption.redeem()`](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53#code) doesn't have any minimum limitation restriction. 
> > @rickkk137 @pkqs90 Not even a duplicate.
> > 
> > Invalid issue.
> > 
> > There is no `min redemption` amount requirement or blocker within the Redeem or Settlement contracts:
> > 
> > * Redemption: [Etherscan link](https://etherscan.io/address/0x31D3F59Ad4aAC0eeE2247c65EBE8Bf6E9E470a53#code)
> > * Settlement: [Etherscan link](https://etherscan.io/address/0x57Dd4E92712b0fBC8d3f3e3645EebCf2600aCef0#code)
> > 
> > The only valid limitation is the one mentioned in issue #100, which specifies a minimum balance requirement (if used as current is 0) within the BUILD token contract.
> > 
> > To reiterate, there is no `min redemption` requirement enforced by the smart contracts on the Ethereum network.
> > 
> > The referenced $250,000 worth of shares redemption is not related to the BUILD token redemption for USDC that can be done on-chain. If we consider this amount, it is also missing the requirement that "it needs to be submitted to the Transfer Agent between 8:00 a.m. and 3:00 p.m."
> > 
> > A brief description of the BUILD to USDC redemption process is provided in section `1.4. USDC Liquidity Facility`.
> > 
> > Additionally, the Steakhouse Financial post is not a Readme or a Specification for the audit; it should only be used to gain a better understanding of how Blackrock Tokenized T-Bills work.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
As I understand, @0xklapouchy is indeed correct here and there's no minimum redemption limit, but the minimal BUIDL amount per investor. Hence, this report is non-issue (unless we're mistaken here).

Planning to accept the second escalation and invalidate the report. The first escalation will be rejected, since it asks for this report to be dup of #100, but this report is invalid.

**Comment by pkqs90** [comment]
Yes, it is invalid. Very weird for the spec and Ondo finance to both assume 250k minimum redemption. But I checked the regulation code, and there is no such thing as "minimum redemption". https://etherscan.deth.net/token/0x7712c34205737192402172409a8F7ccef8aA2AEc#code (Under compliance/ComplanceServiceRegulated.sol)

Please go ahead and invalidate this.

**Comment by 0xklapouchy** [comment]
I want to add something for Midas team:

This fix looks incorrect:
https://github.com/RedDuck-Software/midas-contracts/pull/68

Even if you want to include recommendation from `issue 98`, you need to understood that in this pull request you are using 1 storage value `minBuidlToRedeem` for 2 different checks.

The `minBuidlToRedeem` can be used for min redemption amount, but there is a need for additional `minBuildBalance` value, as this can differ from min redemption. 

For example min redemption can be 250k but min balance can be set to 500k. What then? What if you will be in need to min redeem 500k, how this will look like if contact has 750k BUILD?

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [piken](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/98/#issuecomment-2326694126): accepted
- [rickkk137](https://github.com/sherlock-audit/2024-08-midas-minter-redeemer-judging/issues/98/#issuecomment-2324947239): rejected
